### ISSUE TITLE
SD Card Support

### ISSUE THREAD

**Issue by a16bitsysop** [LibreComputerProjectUserGroup/wiki#1]
Adding list of supported SD cards would be good, I have successfully used a samsung evo plus 128gb sd card with the renegade and a custom kernel (and pi1 and pi3).  But having some issues with a 32gb lexar sd card that boots with the firefly kernel but gets an mmc -110 error initialising sd card when mounting root with a custom kernel.

kernel .config file specifically for each board would help along with the firefly .config firefly use for there kernel.  Or if they are really similar just a generic one for all the boards.

**Comment by pacav69** [comment]
Thanks for your response.
it is recommended using Samsung cards (EVO+) at least 8GB upto 128GB.
I think any SD card that would work with a Raspberry Pi would be suitable, which are class 10.

**Comment by pacav69** [comment]
link for sdcards added
http://lcpugwiki.readthedocs.io/en/latest/

**Comment by jcstaudt** [comment]
Closing issue per 'closed' label. Please re-open if solution unsatisfactory.
